import kubuszok.sbt._
import kubuszok.sbt.KubuszokPlugin.autoImport._
import sbtwelcome.UsefulTask

ThisBuild / packageDoc / publishArtifact := false

val publishSettings = Seq(
  organization := "com.kubuszok",
  homepage := Some(url("https://github.com/kubuszok/lls")),
  organizationHomepage := Some(url("https://kubuszok.com")),
  licenses := Seq("Apache-2.0" -> url("https://www.apache.org/licenses/LICENSE-2.0")),
  scmInfo := Some(
    ScmInfo(
      url("https://github.com/kubuszok/lls/"),
      "scm:git:git@github.com:kubuszok/lls.git"
    )
  ),
  startYear := Some(2025),
  developers := List(
    Developer("MateuszKubuszok", "Mateusz Kubuszok", "", url("https://github.com/MateuszKubuszok"))
  ),
  pomExtra := (
    <issueManagement>
      <system>GitHub issues</system>
      <url>https://github.com/kubuszok/lls/issues</url>
    </issueManagement>
  ),
  projectType := ProjectType.ScalaLibrary
)

val noPublishSettings =
  Seq(projectType := ProjectType.NonPublished)

// --- MiMa settings ---

val mimaSettings = Seq(
  mimaPreviousArtifacts := Set(),
  mimaFailOnNoPrevious := false
)

// --- Modules ---

lazy val root = project
  .in(file("."))
  .settings(LlsSettings.commonSettings *)
  .settings(publishSettings *)
  .settings(noPublishSettings *)
  .aggregate(lls.projectRefs *)
  .aggregate(`lls-bench`.projectRefs *)
  .settings(
    moduleName := "lls-build",
    name := "lls-build",
    description := "Build setup for Low Level Scala",
    logo :=
      s"""Low Level Scala (lls) ${version.value} for Scala ${LlsSettings.scalaVersion} x (JVM, Scala.js, Scala Native)
         |
         |Cross-platform, allocation-conscious utilities: Nullable, MkArray, ArrayView,
         |DynamicArray, ObjectMap, ObjectSet, OrderedMap, OrderedSet, Sort, MathUtils.
         |
         |Projects: lls (JVM/JS/Native), lls-bench (JVM only, JMH benchmarks).
         |""".stripMargin,
    usefulTasks := Seq(
      UsefulTask("projects", "List all projects generated by the build matrix").noAlias,
      UsefulTask("test-coverage", "Run JVM tests with scoverage").noAlias,
      UsefulTask("test-js", "Run Scala.js tests").noAlias,
      UsefulTask("test-native", "Run Scala Native tests").noAlias,
      UsefulTask("lls/test", "Run JVM tests (no coverage)").noAlias,
      UsefulTask("lls/publishLocal ; llsJS/publishLocal ; llsNative/publishLocal", "Publish all platforms locally")
        .alias("publish-local-for-tests"),
      UsefulTask("ci-release", "Publish signed artifacts to Maven Central").noAlias,
      UsefulTask("scalafmtCheckAll; scalafmtSbtCheck", "Check formatting").noAlias
    )
  )

lazy val lls = (projectMatrix in file("lls"))
  .defaultAxes(VirtualAxis.jvm, VirtualAxis.scalaABIVersion(LlsSettings.scalaVersion))
  .disablePlugins(WelcomePlugin)
  .settings(LlsSettings.commonSettings *)
  .settings(publishSettings *)
  .settings(mimaSettings *)
  .settings(
    moduleName := "lls",
    name := "lls",
    description := "Low Level Scala — cross-platform, allocation-conscious utilities",
    libraryDependencies ++= Seq(
      "org.scalameta"  %%% "munit"            % LlsSettings.versions.munit           % Test,
      "org.scalameta"  %%% "munit-scalacheck" % LlsSettings.versions.munitScalacheck % Test,
      "org.scalacheck" %%% "scalacheck"       % LlsSettings.versions.scalacheck      % Test
    )
  )
  .jvmPlatform(scalaVersions = Seq(LlsSettings.scalaVersion), settings = LlsSettings.jvmSettings)
  .jsPlatform(scalaVersions = Seq(LlsSettings.scalaVersion), settings = LlsSettings.jsSettings)
  .nativePlatform(scalaVersions = Seq(LlsSettings.scalaVersion), settings = LlsSettings.nativeSettings)

lazy val `lls-bench` = (projectMatrix in file("lls-bench"))
  .defaultAxes(VirtualAxis.jvm, VirtualAxis.scalaABIVersion(LlsSettings.scalaVersion))
  .enablePlugins(JmhPlugin)
  .disablePlugins(WelcomePlugin)
  .settings(LlsSettings.commonSettings *)
  .settings(noPublishSettings *)
  .settings(
    moduleName := "lls-bench",
    name := "lls-bench",
    description := "JMH benchmarks for Low Level Scala",
    scalacOptions --= Seq("-Wunused:imports,privates,locals,patvars,nowarn")
  )
  .dependsOn(lls)
  .jvmPlatform(scalaVersions = Seq(LlsSettings.scalaVersion), settings = LlsSettings.jvmSettings)

// --- CI command aliases ---

addCommandAlias("test-coverage", "; coverage; lls/test; coverageAggregate; coverageOff")
addCommandAlias("test-js", "llsJS/test")
addCommandAlias("test-native", "llsNative/test")
